# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.5"
manifest_format = "2.0"
project_hash = "7980b103a2be8b0efa865f61b79e0514ff9031a0"

[[deps.BBSim]]
path = "BBSim"
uuid = "2f9dc5a3-ddd6-4aa1-9c38-223866a68bd9"
version = "0.1.0"
